swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for org.edgegallery.atp.interfaces.TestCaseController"
  x-java-interface: "cse.gen.edgegallery.mec_atp.testCase.TestCaseControllerIntf"
basePath: "/edgegallery/atp/v1"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /testcases:
    get:
      tags:
      - "APT Test Case Controller"
      summary: "get all test cases."
      operationId: "getAllTestCases"
      produces:
      - "application/json"
      parameters:
      - name: "type"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/TaskRequest"
        404:
          description: "microservice not found"
          schema:
            type: "string"
        415:
          description: "Unprocessable MicroServiceInfo Entity "
          schema:
            type: "string"
        500:
          description: "resource grant error"
          schema:
            type: "string"
definitions:
  TaskRequest:
    type: "object"
    properties:
      id:
        type: "string"
      appName:
        type: "string"
      appVersion:
        type: "string"
      status:
        type: "string"
      createTime:
        type: "string"
        format: "date-time"
      endTime:
        type: "string"
        format: "date-time"
      user:
        $ref: "#/definitions/User"
      testCaseDetail:
        $ref: "#/definitions/TestCaseDetail"
      accessToken:
        type: "string"
    x-java-class: "org.edgegallery.atp.model.task.TaskRequest"
  TestCaseDetail:
    type: "object"
    properties:
      virusScanningTest:
        type: "array"
        items:
          type: "object"
          additionalProperties:
            $ref: "#/definitions/TestCaseResult"
      complianceTest:
        type: "array"
        items:
          type: "object"
          additionalProperties:
            $ref: "#/definitions/TestCaseResult"
      sandboxTest:
        type: "array"
        items:
          type: "object"
          additionalProperties:
            $ref: "#/definitions/TestCaseResult"
    x-java-class: "org.edgegallery.atp.model.testcase.TestCaseDetail"
  TestCaseResult:
    type: "object"
    properties:
      result:
        type: "string"
      reason:
        type: "string"
    x-java-class: "org.edgegallery.atp.model.testcase.TestCaseResult"
  User:
    type: "object"
    properties:
      userId:
        type: "string"
      userName:
        type: "string"
    x-java-class: "org.edgegallery.atp.model.user.User"