---
swagger: '2.0'
info:
  description: APPLCM REST API
  version: 1.0.0
  title: HUAWEI APPLCM REST API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:8094
basePath: "/"
tags:
- name: app-lcm-controller
  description: Operation for applcm system
paths:
  "/lcmcontroller/v1/app_instances/{appInstanceId}":
    get:
      tags:
      - app-lcm-controller
      summary: get Application list
      operationId: getApplicationListUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: appInstanceId
        in: path
        description: app_instance_id
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/lcmcontroller/v1/app_instance/{appInstanceId}/instantiate":
    post:
      tags:
      - app-lcm-controller
      summary: instantiate application
      operationId: instantiateApplicationUsingPOST
      consumes:
      - multipart/form-data
      produces:
      - "*/*"
      parameters:
      - name: appInstanceId
        in: path
        description: app_instance_id
        required: true
        type: string
      - name: hostIp
        in: query
        description: host_ip
        required: true
        type: string
      - name: file
        in: formData
        description: file
        required: true
        type: file
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/lcmcontroller/v1/configuration":
    post:
      tags:
      - app-lcm-controller
      summary: Upload config file
      operationId: uploadK8sConfigUsingPOST
      consumes:
      - multipart/form-data
      produces:
      - "*/*"
      parameters:
      - name: hostIp
        in: path
        description: host_ip
        required: true
        type: string
      - name: configFile
        in: formData
        description: file
        required: true
        type: file
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/lcmcontroller/v1/configuration":
    delete:
      tags:
      - app-lcm-controller
      summary: Remove config file
      operationId: removeK8sConfigUsingPOST
      consumes:
      - multipart/form-data
      produces:
      - "*/*"
      parameters:
      - name: hostIp
        in: path
        description: host_ip
        required: true
        type: string
      responses:
        '204':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/lcmcontroller/v1/mep_capabilities/:hostIp":
    get:
      tags:
      - app-lcm-controller
      summary: get MEP capabilities
      operationId: getMepCapabilitiesUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: tenant_id
        in: path
        description: tenant_id
        required: true
        type: string
      - name: hostIp
        in: path
        description: host_ip
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  "/lcmcontroller/v1/app_instances/{appInstanceId}/terminate":
    post:
      tags:
      - app-lcm-controller
      summary: Terminate application
      operationId: terminateApplicationUsingDELETE
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: appInstanceId
        in: path
        description: app_instance_id
        required: true
        type: string
      - name: hostIp
        in: path
        description: host_ip
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  "/lcmcontroller/v1/kpi/{hostIp}":
    get:
      tags:
      - app-lcm-controller
      summary: get CPU/ Memory and file system size
      operationId: getResourceInfoUsingGET
      consumes:
      - application/json
      produces:
      - "*/*"
      parameters:
      - name: tenant_id
        in: path
        description: tenant_id
        required: true
        type: string
      - name: hostIp
        in: path
        description: host_ip
        required: true
        type: string
      - name: query
        in: query
        description: query
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
